[training]
exten => 900,1,ExecIf($[${STAT(e,/provision/maintenance)}]?Hangup())
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()
exten => _10[1-4],1,ExecIf($[${STAT(e,/provision/maintenance)}]?Hangup())
 same => n,Set(SERVICE_NUMBER=${EXTEN})
 same => n,Goto(training-service,s,1)
exten => _99X.,1,ExecIf($[${STAT(e,/provision/maintenance)}]?Hangup())
 same => n,GotoIf($["${EXTEN}" != "99${ARM_USER_ID}"]?deny)
 same => n,Answer()
 same => n,ConfBridge(arm112-${ARM_USER_ID},training_bridge,training_user)
 same => n(deny),Hangup()
[training-playback]
exten => s,1,ExecIf($[${STAT(e,/provision/maintenance)}]?Hangup())
 same => n,Answer()
 same => n,Set(CHANNEL(language)=ru)
 same => n,MixMonitor(/media/recording-${ARM_RUN_ID}-${ARM_CALL_ID}.wav)
 same => n,Wait(1)
 same => n,Playback(/media/${ARM_SOUND})
 same => n,Wait(3)
 same => n,Hangup()

[training-service]
exten => s,1,ExecIf($[${STAT(e,/provision/maintenance)}]?Hangup())
 same => n,Answer()
 same => n,Set(SERVICE_SOUND=${DB(arm112/service${SERVICE_NUMBER})})
 same => n,GotoIf($["${SERVICE_SOUND}" = ""]?echo)
 same => n,Wait(1)
 same => n,Playback(/media/${SERVICE_SOUND})
 same => n(echo),Echo()
 same => n,Hangup()
